// Flat C exports observed in NTASN1.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef NTASN1_C_H
#define NTASN1_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: #ordinal56 (ABI unverified)
// Export: ASN1DER_DecFileTimeGeneralized (ABI unverified)
// Export: #ordinal40 (ABI unverified)
// Export: ASN1DER_DecExplicitTag (ABI unverified)
// Export: #ordinal61 (ABI unverified)
// Export: ASN1BER_DecExplicitTag (ABI unverified)
// Export: #ordinal30 (ABI unverified)
// Export: ASN1DER_EncUTF8String (ABI unverified)
// Export: #ordinal16 (ABI unverified)
// Export: ASN1DER_EncExplicitTag (ABI unverified)
// Export: #ordinal60 (ABI unverified)
// Export: ASN1BER_DecTagLength (ABI unverified)
// Export: #ordinal51 (ABI unverified)
// Export: ASN1DER_DecUTF8String (ABI unverified)
// Export: #ordinal3 (ABI unverified)
// Export: RtlAsn1Decode (ABI unverified)
// Export: #ordinal4 (ABI unverified)
// Export: RtlAsn1DecodeAndAllocate (ABI unverified)
// Export: #ordinal10 (ABI unverified)
// Export: ASN1_DecodeObject (ABI unverified)
// Export: #ordinal41 (ABI unverified)
// Export: ASN1DER_DecSequenceOfAny (ABI unverified)
// Export: #ordinal38 (ABI unverified)
// Export: ASN1DER_DecPeekTag (ABI unverified)
// Export: #ordinal19 (ABI unverified)
// Export: ASN1DER_EncInteger (ABI unverified)
// Export: #ordinal32 (ABI unverified)
// Export: ASN1DER_EncSystemTimeGeneralized (ABI unverified)
// Export: #ordinal22 (ABI unverified)
// Export: ASN1DER_EncOctetString (ABI unverified)
// Export: #ordinal42 (ABI unverified)
// Export: ASN1DER_DecInteger32 (ABI unverified)
// Export: #ordinal5 (ABI unverified)
// Export: RtlAsn1GetModuleHandle (ABI unverified)
// Export: #ordinal18 (ABI unverified)
// Export: ASN1DER_EncCanonicalInteger (ABI unverified)
// Export: #ordinal7 (ABI unverified)
// Export: ASN1_FindOidInfoByEoid (ABI unverified)
// Export: #ordinal37 (ABI unverified)
// Export: ASN1DER_DecTagLength (ABI unverified)
// Export: #ordinal2 (ABI unverified)
// Export: RtlAsn1EncodeAndAllocate (ABI unverified)
// Export: #ordinal12 (ABI unverified)
// Export: ASN1_FindObjectEntry (ABI unverified)
// Export: #ordinal6 (ABI unverified)
// Export: ASN1_FindOidInfo (ABI unverified)
// Export: #ordinal9 (ABI unverified)
// Export: CryptDecodeObjectEx (ABI unverified)
// Export: #ordinal8 (ABI unverified)
// Export: CryptEncodeObjectEx (ABI unverified)
// Export: #ordinal53 (ABI unverified)
// Export: ASN1DER_DecBitString (ABI unverified)
// Export: #ordinal45 (ABI unverified)
// Export: ASN1DER_DecBool (ABI unverified)
// Export: #ordinal46 (ABI unverified)
// Export: ASN1DER_DecChar16String (ABI unverified)
// Export: #ordinal47 (ABI unverified)
// Export: ASN1DER_DecChar32String (ABI unverified)
// Export: #ordinal49 (ABI unverified)
// Export: ASN1DER_DecChar8StringA (ABI unverified)
// Export: #ordinal50 (ABI unverified)
// Export: ASN1DER_DecChar8StringW (ABI unverified)
// Export: #ordinal55 (ABI unverified)
// Export: ASN1DER_DecFileTime (ABI unverified)
// Export: #ordinal57 (ABI unverified)
// Export: ASN1DER_DecFileTimeUTC (ABI unverified)
// Export: #ordinal36 (ABI unverified)
// Export: ASN1DER_DecLength32 (ABI unverified)
// Export: #ordinal43 (ABI unverified)
// Export: ASN1DER_DecMultiByteInteger (ABI unverified)
// Export: #ordinal44 (ABI unverified)
// Export: ASN1DER_DecNull (ABI unverified)
// Export: #ordinal54 (ABI unverified)
// Export: ASN1DER_DecObjectIdentifierStr (ABI unverified)
// Export: #ordinal52 (ABI unverified)
// Export: ASN1DER_DecOctetString (ABI unverified)
// Export: #ordinal39 (ABI unverified)
// Export: ASN1DER_DecTag (ABI unverified)
// Export: #ordinal58 (ABI unverified)
// Export: ASN1DER_EncodedOIDToDotValA (ABI unverified)
// Export: #ordinal59 (ABI unverified)
// Export: ASN1DER_EncodedOIDToDotValW (ABI unverified)
// Export: #ordinal24 (ABI unverified)
// Export: ASN1DER_EncBitString (ABI unverified)
// Export: #ordinal21 (ABI unverified)
// Export: ASN1DER_EncBool (ABI unverified)
// Export: #ordinal23 (ABI unverified)
// Export: ASN1DER_EncCanonicalBitString (ABI unverified)
// Export: #ordinal25 (ABI unverified)
// Export: ASN1DER_EncChar16String (ABI unverified)
// Export: #ordinal26 (ABI unverified)
// Export: ASN1DER_EncChar32String (ABI unverified)
// Export: #ordinal28 (ABI unverified)
// Export: ASN1DER_EncChar8StringA (ABI unverified)
// Export: #ordinal29 (ABI unverified)
// Export: ASN1DER_EncChar8StringW (ABI unverified)
// Export: #ordinal33 (ABI unverified)
// Export: ASN1DER_EncFileTimeGeneralized (ABI unverified)
// Export: #ordinal35 (ABI unverified)
// Export: ASN1DER_EncFileTimeUTC (ABI unverified)
// Export: #ordinal14 (ABI unverified)
// Export: ASN1DER_EncLength32 (ABI unverified)
// Export: #ordinal20 (ABI unverified)
// Export: ASN1DER_EncNull (ABI unverified)
// Export: #ordinal31 (ABI unverified)
// Export: ASN1DER_EncObjectIdentifierStr (ABI unverified)
// Export: #ordinal34 (ABI unverified)
// Export: ASN1DER_EncSystemTimeUTC (ABI unverified)
// Export: #ordinal15 (ABI unverified)
// Export: ASN1DER_EncTag (ABI unverified)
// Export: #ordinal17 (ABI unverified)
// Export: ASN1DER_EncUnsignedInteger32 (ABI unverified)
// Export: #ordinal48 (ABI unverified)
// Export: ASN1DER_DecChar32StringW (ABI unverified)
// Export: #ordinal27 (ABI unverified)
// Export: ASN1DER_EncChar32StringW (ABI unverified)
// Export: #ordinal11 (ABI unverified)
// Export: ASN1_EncodeObject (ABI unverified)
// Export: #ordinal1 (ABI unverified)
// Export: RtlAsn1Encode (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // NTASN1_C_H
